version: "3"
services:
    core:
        build: ./docker/dev/php
        image: wifa:core
        container_name: core
        expose:
            - "9000"
        volumes:
            - ./core:/var/www
        environment:
            XDEBUG_CONFIG: "remote_host=172.29.175.8"
            PHP_IDE_CONFIG: "serverName=wifa.local"
        tty: true
        hostname: core
        networks:
            - wifa_net
    client:
        build: ./docker/dev/node
        image: wifa:client
        container_name: client
        ports:
            - "8601:8080"
        volumes:
            - ./client:/var/www/client
        networks:
            - wifa_net
        hostname: client
    nginx:
        build: ./docker/dev/nginx
        image: wifa:nginx
        container_name: nginx
        environment:
            CORE_HOST: api.wifa.local
            CLIENT_HOST: wifa.local
        ports:
            - "8600:80"
        links:
            - core
            - client
        volumes:
            - ./core/var/log:/var/log/nginx
            - ./core/public:/var/www/core/
        networks:
            - wifa_net
    db:
        build: ./docker/dev/db
        container_name: db
        image: wifa:db
        ports:
            - "8602:27017"
        hostname: db
        networks:
            - wifa_net

networks:
    wifa_net:
        external: true