shaygan_telegram_bot_api:
    token: '%env(string:TELEGRAM_BOT_TOKEN)%'
    webhook:
        domain: '%env(string:TELEGRAM_BOT_WEBHOOK_DOMAIN)%'# example.com
        path_prefix: ~ # you can add prefix, if your web site is not on the root
        update_receiver: shaygan.my_update_receiver # sample update receiver